{% set name = "thevenin" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01667169ca238ff9af138af969b2c94b525633ba1df697bc9cd62c2053ab802b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - matplotlib-base
    - ruamel.yaml
    - scikit-sundae >=1.0.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - thevenin

about:
  home: https://github.com/NREL/thevenin
  summary: 'Equivalent circuit models in Python.'
  description: |
    This package is a wrapper for the well-known Thevenin equivalent circuit
    model. The model is comprised of a single series reistor followed by any
    number of parallel resistor-capacitor pairs. Models can run constant or
    dynamic current-, voltage-, or power-controlled loads in sequential steps.
    Resistor and capacitor parameter values are set up to be functions of both
    state of charge and temperature.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://thevenin.readthedocs.io/
  dev_url: https://github.com/NREL/thevenin

extra:
  recipe-maintainers:
    - c-randall
